name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
      - name: Fazer commit do arquivo ao repositório
        env:
            ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
        run: |
              git config --global user.email "freitax.li@gmail.com"
              git config --global user.name "Fernando Freitas"
              git add main.pdf
              git commit -m "adicionar arquivo PDF"
              git push -u origin main
